[package]
name = "media-server-1"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

[dependencies]
actix-files = "^0.5.0"
actix-web = "^3.3.2"
derive_more = "^0.99.11"
dotenv = "^0.15.0"
env_logger = "^0.8.2"
regex = "^1.4.3"
serde = "^1.0.119"
toml = "^0.5.8"
